### ISSUE TITLE
Document Contributing Examples

### ISSUE THREAD

**Issue by vinckr** [ory/examples#26]
We should add documentation how to contribute new examples. 

Draft PR: https://github.com/ory/examples/pull/25

We can add a short section to the README or add it to the general template [CONTRIBUTING doc](https://github.com/ory/meta/blob/master/templates/repository/common/CONTRIBUTING.md) or write a seperate CONTRIBUTING for this repo, what do you think @kevgo ?

**Comment by kevgo** [comment]
The general breakup I use for documentation is:

- **README.md** is for end users. It describes the features, how to install, how to start
- **DEVELOPMENT.md** is for developers: how to hack on this, how to run tests, where is which code
- **CONTRIBUTING.md** is for contributors, i.e. developers who contribute their modifications back. It is shown when making the first PR and states needed legalese like "Before we can accept this code from you, you have to agree to our COC and CLA". 

So, my vote on where to put this goes to DEVELOPMENT.md.

**Comment by vinckr** [comment]
Sorry for going over you here Kevin, 
but I went ahead and added a [short section](https://github.com/ory/examples/blob/master/CONTRIBUTING.md#contribute-examples) to the general contributing template, that is copied to all repos. I had to move a bit fast to get the word out, but we can still think of improvements down the line. 

While I think your distinction makes sense, I dont see why it would be in the DEVELOPMENT.md in this case - this is explicitly a guide how to __contribute__ examples. I think all legalities are covered by our contributor license agreement.

IMO CONTRIBUTING.md should cover everything that is useful to people who want to contribute - long before they open the first pull request CONTRIBUTING shows the conduct and general process of contributions. Most importantly IMO it also outlines all the ways that you can contribute without ever writing a line of code or opening a PR. 

Closing since the initial issue is resolved, and subsequent improvements to the doc would best be discussed in ory/meta

**Comment by kevgo** [comment]
No worries, there are many correct answers here. That was just my take on it. You make an excellent point that CONTRIBUTING.md is a natural place where people look for how to contribute examples. Good choice!
