### ISSUE TITLE
ory/hydra scalability, running multiple instances of ory/hydra

### ISSUE THREAD

**Issue by vinckr** [ory/examples#53]
## Q: Where can I get documentation on running multiple instances of Hydra?

My company is thinking about adopting Hydra. There is a performance benchmark including data at https://www.ory.sh/docs/next/performance/hydra
and some information on how to scale hydra. 
Where can I get documentation on running multiple instances of Hydra?

## A: Hydra scales according to 12 factor principles. Just add another instance with the same config. 

Please check the documentation section for 12 factor principles for more information:
https://www.ory.sh/docs/ecosystem/cloud-native
There is also some information on collecting statistics in the section on [prometheus](https://github.com/prometheus) in the five minute tutorial: 
https://www.ory.sh/docs/hydra/5min-tutorial

Handle: @killa#7335
Source: Discord/ory/general
Date: 20190103 01:06

**Comment by aeneasr** [comment]
I think the FAQ section would be a better place to keep track of this!

https://github.com/ory/docs/blob/master/docs/hydra/faq.md

We can also create FAQ sections for each project and/or all projects
