### ISSUE TITLE
Automated tests for community examples

### ISSUE THREAD

**Issue by vinckr** [ory/examples#8]
Would be good if we test the examples and make sure they work.

[Playwright](https://github.com/microsoft/playwright), which we use also in the /docs is probably the best choice.

- [x] [Example Django App using Ory Cloud](https://github.com/ory/examples/tree/master/django-ory-cloud)
- [ ] [Example Flask App using Ory Kratos and Ory Keto](https://github.com/ory/examples/tree/master/kratos-keto-flask)
- [ ] [Example with Kubernetes using Ory Kratos, Ory Keto and Ory Oathkeeper](https://github.com/ory/examples/tree/master/kratos-keto-oathkeeper-k8s)
- [ ] [Example with Supabase using Ory Kratos and Ory Oathkeeper](https://github.com/ory/examples/tree/master/kratos-keto-oathkeeper-supabase)
- [ ] [Example with Supabase using Ory Cloud](https://github.com/ory/examples/tree/master/supabase-ory-cloud)
- [ ] [Example API Gateway with Kong using Ory Kratos & Ory Oathkeeper](https://github.com/ory/examples/tree/master/kratos-oathkeeper-kong)
- [ ] [Example configuration for Ory Kratos & Nginx](https://github.com/ory/examples/tree/master/kratos-nginx)
- [ ] [Example configuration for Ory Hydra & Nginx](https://github.com/ory/examples/tree/master/hydra-nginx)
- [ ] [Example configurations for Ory Oathkeeper](https://github.com/ory/examples/tree/master/oathkeeper)

**Comment by kevgo** [comment]
https://github.com/kevgo/text-runner is a tool built specifically for this use case. I'm happy to set it up and implement the tests in it. Some things that Text-Runner can do:

- run shell commands that the documentation asks the user to run
- create files that the documentation asks the reader to create
- check that URLs mentioned in the documentation work
- fire up Playwright, open URLs mentioned in the document, take a screenshot of the actual running application UI, and compare it to the screenshot in the documentation

**Comment by vinckr** [comment]
Awesome that is great to hear! 
We probably have to check for each example but even the ones with Ory Cloud should be doable - just using the CLI we can easily create dummy projects for testing. 
Maybe we just start with the "django ory cloud" example, that seems fairly easy and then add it to the others over time, wdyt? 
Looking forward to seeing text-runner more in action 💪

**Comment by kevgo** [comment]
Sounds good. To clarify, Text-Runner is for verifying the instructions in the documentation (README.md).

[Cucumber](https://cucumber.io) could be used to verify that the different example applications behave exactly the same, for example that creating posts works.

**Comment by vinckr** [comment]
Ah I see, so we start with text-runner and see if the instructions are correct and then later on add Cucumber to make it more robust?
