### ISSUE TITLE
readme template/structure

### ISSUE THREAD

**Issue by vinckr** [ory/examples#9]
the readme for each example should have a uniform structure, 
same headings e.g. 
```md

# Title 

Description

Link to blogpost

## Overview

Maybe architecture diagram, more detailed explanation than in description, links to relevant resources.

### Prerequisites

what you need to run this

## Develop

instructions how to run example locally

## Deploy

instructions or “next steps” to run example in 
cloud

## Run tests

## Contribute

```

**Comment by vinckr** [comment]
@gen1us2k @kevgo 
This should be a template for all READMEs in the example repo, so we have a clear structure and uniform content for all of them. 
Let me know your thoughts on this. 

We should not find the "perfect" solution, but a really good one before we write 20 READMEs :-)

**Comment by kevgo** [comment]
I love this idea. Once we agree on the structure, I can set up automation that enforces this documentation structure.
